# Generated by Django 5.0.7 on 2025-01-19 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('query', models.TextField(max_length=500)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('overall_experiance', models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Average'), ('2', 'Poor'), ('2', 'Vary Poor')], default=5, max_length=1)),
                ('content_quality', models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Average'), ('2', 'Poor'), ('2', 'Vary Poor')], default=5, max_length=1)),
                ('design_usability', models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Average'), ('2', 'Poor'), ('2', 'Vary Poor')], default=5, max_length=1)),
                ('most_enjoyable_thing', models.TextField(max_length=300)),
                ('suggestions', models.TextField(max_length=200)),
                ('encountered_any_issues', models.CharField(choices=[('1', 'Design Problem'), ('2', 'Content Erro'), ('3', 'Bug/Technical Issue'), ('4', 'Other'), ('5', 'None')], default=5, max_length=1)),
                ('description_of_issue', models.TextField(max_length=300)),
                ('additional_comment', models.TextField(max_length=300)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('blog_list_image', models.ImageField(upload_to='static/Blog_images/ListImage')),
                ('detail_image', models.ImageField(upload_to='static/Blog_images/detailImage')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static/blog_pdfs/pdf/')),
                ('slug', models.SlugField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('catogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.catogery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCQ_Question',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=300)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('correct_ans', models.CharField(max_length=50)),
                ('explanation', models.TextField(max_length=500)),
                ('catogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.catogery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
